# Generated by Django 5.2.12 on 2026-03-28 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaObject',
            fields=[
                ('handle', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gramps_id', models.CharField(blank=True, default='', max_length=50, unique=True)),
                ('change', models.FloatField(default=0, help_text='Unix timestamp of last modification')),
                ('private', models.BooleanField(default=False)),
                ('tag_list', models.JSONField(blank=True, default=list, help_text='List of Tag handles')),
                ('path', models.CharField(blank=True, default='', max_length=1000)),
                ('mime', models.CharField(blank=True, default='', max_length=100)),
                ('desc', models.CharField(blank=True, default='', max_length=500)),
                ('checksum', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.JSONField(blank=True, default=dict)),
                ('attribute_list', models.JSONField(blank=True, default=list)),
                ('citation_list', models.JSONField(blank=True, default=list)),
                ('note_list', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'media object',
                'verbose_name_plural': 'media objects',
                'db_table': 'gramps_media',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('handle', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gramps_id', models.CharField(blank=True, default='', max_length=50, unique=True)),
                ('change', models.FloatField(default=0, help_text='Unix timestamp of last modification')),
                ('private', models.BooleanField(default=False)),
                ('tag_list', models.JSONField(blank=True, default=list, help_text='List of Tag handles')),
                ('text', models.JSONField(blank=True, default=dict, help_text='{string: "text content", tags: [{name, value, ranges}]}')),
                ('format', models.IntegerField(default=0, help_text='0=flowed, 1=formatted')),
                ('type', models.CharField(blank=True, default='General', max_length=100)),
            ],
            options={
                'db_table': 'gramps_note',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('handle', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gramps_id', models.CharField(blank=True, default='', max_length=50, unique=True)),
                ('change', models.FloatField(default=0, help_text='Unix timestamp of last modification')),
                ('private', models.BooleanField(default=False)),
                ('tag_list', models.JSONField(blank=True, default=list, help_text='List of Tag handles')),
                ('gender', models.IntegerField(choices=[(0, 'Female'), (1, 'Male'), (2, 'Unknown'), (3, 'Other')], default=2)),
                ('primary_name', models.JSONField(blank=True, default=dict)),
                ('alternate_names', models.JSONField(blank=True, default=list)),
                ('event_ref_list', models.JSONField(blank=True, default=list, help_text='[{ref: event_handle, role, private, note_list, attribute_list}]')),
                ('family_list', models.JSONField(blank=True, default=list, help_text='List of Family handles where person is a parent')),
                ('parent_family_list', models.JSONField(blank=True, default=list, help_text='List of Family handles where person is a child')),
                ('person_ref_list', models.JSONField(blank=True, default=list, help_text='[{ref: person_handle, rel, private, note_list, citation_list}]')),
                ('media_list', models.JSONField(blank=True, default=list, help_text='[{ref: media_handle, rect, private, note_list, citation_list, attribute_list}]')),
                ('address_list', models.JSONField(blank=True, default=list)),
                ('attribute_list', models.JSONField(blank=True, default=list)),
                ('citation_list', models.JSONField(blank=True, default=list, help_text='List of Citation handles')),
                ('note_list', models.JSONField(blank=True, default=list, help_text='List of Note handles')),
                ('urls', models.JSONField(blank=True, default=list)),
                ('lds_ord_list', models.JSONField(blank=True, default=list)),
                ('birth_ref_index', models.IntegerField(default=-1)),
                ('death_ref_index', models.IntegerField(default=-1)),
            ],
            options={
                'verbose_name_plural': 'people',
                'db_table': 'gramps_person',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('handle', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gramps_id', models.CharField(blank=True, default='', max_length=50, unique=True)),
                ('change', models.FloatField(default=0, help_text='Unix timestamp of last modification')),
                ('private', models.BooleanField(default=False)),
                ('tag_list', models.JSONField(blank=True, default=list, help_text='List of Tag handles')),
                ('name', models.JSONField(blank=True, default=dict, help_text='{value, lang, date}')),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('alt_names', models.JSONField(blank=True, default=list)),
                ('place_type', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('lat', models.CharField(blank=True, default='', max_length=50)),
                ('long', models.CharField(blank=True, default='', max_length=50)),
                ('placeref_list', models.JSONField(blank=True, default=list, help_text='[{ref: place_handle, date}] - parent places in hierarchy')),
                ('alt_loc', models.JSONField(blank=True, default=list)),
                ('urls', models.JSONField(blank=True, default=list)),
                ('media_list', models.JSONField(blank=True, default=list)),
                ('citation_list', models.JSONField(blank=True, default=list)),
                ('note_list', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'gramps_place',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('handle', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gramps_id', models.CharField(blank=True, default='', max_length=50, unique=True)),
                ('change', models.FloatField(default=0, help_text='Unix timestamp of last modification')),
                ('private', models.BooleanField(default=False)),
                ('tag_list', models.JSONField(blank=True, default=list, help_text='List of Tag handles')),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('type', models.CharField(blank=True, default='', max_length=100)),
                ('address_list', models.JSONField(blank=True, default=list)),
                ('urls', models.JSONField(blank=True, default=list)),
                ('note_list', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'repositories',
                'db_table': 'gramps_repository',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('handle', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gramps_id', models.CharField(blank=True, default='', max_length=50, unique=True)),
                ('change', models.FloatField(default=0, help_text='Unix timestamp of last modification')),
                ('private', models.BooleanField(default=False)),
                ('tag_list', models.JSONField(blank=True, default=list, help_text='List of Tag handles')),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('author', models.CharField(blank=True, default='', max_length=500)),
                ('pubinfo', models.TextField(blank=True, default='')),
                ('abbrev', models.CharField(blank=True, default='', max_length=200)),
                ('reporef_list', models.JSONField(blank=True, default=list, help_text='[{ref: repo_handle, call_number, media_type, private, note_list}]')),
                ('media_list', models.JSONField(blank=True, default=list)),
                ('note_list', models.JSONField(blank=True, default=list)),
                ('attribute_list', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'gramps_source',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('handle', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(blank=True, default='#000000000000', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('change', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'gramps_tag',
            },
        ),
        migrations.CreateModel(
            name='BacklinkIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_handle', models.CharField(db_index=True, max_length=50)),
                ('source_type', models.CharField(db_index=True, max_length=20)),
                ('target_handle', models.CharField(db_index=True, max_length=50)),
                ('target_type', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'db_table': 'gramps_backlink_index',
                'indexes': [models.Index(fields=['target_handle', 'target_type'], name='gramps_back_target__50b9f4_idx'), models.Index(fields=['source_handle', 'source_type'], name='gramps_back_source__f617b4_idx')],
                'unique_together': {('source_handle', 'source_type', 'target_handle', 'target_type')},
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('handle', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gramps_id', models.CharField(blank=True, default='', max_length=50, unique=True)),
                ('change', models.FloatField(default=0, help_text='Unix timestamp of last modification')),
                ('private', models.BooleanField(default=False)),
                ('tag_list', models.JSONField(blank=True, default=list, help_text='List of Tag handles')),
                ('type', models.CharField(blank=True, default='Married', max_length=50)),
                ('child_ref_list', models.JSONField(blank=True, default=list, help_text='[{ref: person_handle, frel, mrel, private, note_list, citation_list}]')),
                ('event_ref_list', models.JSONField(blank=True, default=list)),
                ('media_list', models.JSONField(blank=True, default=list)),
                ('attribute_list', models.JSONField(blank=True, default=list)),
                ('citation_list', models.JSONField(blank=True, default=list)),
                ('note_list', models.JSONField(blank=True, default=list)),
                ('lds_ord_list', models.JSONField(blank=True, default=list)),
                ('father_handle', models.ForeignKey(blank=True, db_column='father_handle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_as_father', to='core.person')),
                ('mother_handle', models.ForeignKey(blank=True, db_column='mother_handle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_as_mother', to='core.person')),
            ],
            options={
                'verbose_name_plural': 'families',
                'db_table': 'gramps_family',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('handle', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gramps_id', models.CharField(blank=True, default='', max_length=50, unique=True)),
                ('change', models.FloatField(default=0, help_text='Unix timestamp of last modification')),
                ('private', models.BooleanField(default=False)),
                ('tag_list', models.JSONField(blank=True, default=list, help_text='List of Tag handles')),
                ('type', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.JSONField(blank=True, default=dict, help_text='{calendar, dateval, modifier, quality, year, sortval, text, newyear}')),
                ('description', models.TextField(blank=True, default='')),
                ('citation_list', models.JSONField(blank=True, default=list)),
                ('media_list', models.JSONField(blank=True, default=list)),
                ('note_list', models.JSONField(blank=True, default=list)),
                ('attribute_list', models.JSONField(blank=True, default=list)),
                ('place', models.ForeignKey(blank=True, db_column='place', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.place')),
            ],
            options={
                'db_table': 'gramps_event',
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('handle', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gramps_id', models.CharField(blank=True, default='', max_length=50, unique=True)),
                ('change', models.FloatField(default=0, help_text='Unix timestamp of last modification')),
                ('private', models.BooleanField(default=False)),
                ('tag_list', models.JSONField(blank=True, default=list, help_text='List of Tag handles')),
                ('page', models.CharField(blank=True, default='', max_length=500)),
                ('date', models.JSONField(blank=True, default=dict)),
                ('confidence', models.IntegerField(default=2)),
                ('media_list', models.JSONField(blank=True, default=list)),
                ('note_list', models.JSONField(blank=True, default=list)),
                ('attribute_list', models.JSONField(blank=True, default=list)),
                ('source_handle', models.ForeignKey(blank=True, db_column='source_handle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citations', to='core.source')),
            ],
            options={
                'db_table': 'gramps_citation',
            },
        ),
    ]
