# Generated by Django 6.1.2 on 2026-10-10 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_citation_gramps_id_alter_event_gramps_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(db_index=True, help_text='Unix timestamp of the commit')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('undone', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gramps_transaction',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('obj_class', models.CharField(help_text='Person, Family, ..., Media, Note, Tag', max_length=20)),
                ('obj_handle', models.CharField(db_index=True, max_length=50)),
                ('trans_type', models.IntegerField(choices=[(0, 'add'), (1, 'update'), (2, 'delete')])),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='core.transaction')),
            ],
            options={
                'db_table': 'gramps_transaction_change',
                'ordering': ['transaction_id', 'order'],
            },
        ),
    ]
