# Generated by Django 6.1.2 on 2026-10-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gramps_config',
            },
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(default='PENDING', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('info', models.JSONField(blank=True, null=True)),
                ('created', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'gramps_task_result',
            },
        ),
    ]
