# Generated by Django 5.2.12 on 2026-03-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrampsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('role', models.IntegerField(choices=[(-1, 'Disabled'), (-2, 'Unconfirmed'), (0, 'Guest'), (1, 'Member'), (2, 'Contributor'), (3, 'Editor'), (4, 'Owner'), (5, 'Admin')], default=0)),
                ('tree', models.CharField(blank=True, default='', help_text='Tree identifier for multi-tree support', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gramps_user',
            },
        ),
    ]
